### ISSUE TITLE
liblock.c  mutex_cond_wait() bug report

### ISSUE THREAD

**Issue by CMShuyuhui** [gozfree/libraries#10]
liblock.c   line 237 and 238 in the  mutex_cond_wait() function:

ts.tv_sec += ms / 1000;
ts.tv_nsec += (ms % 1000) \* 1000000;

But personally , I think it should be : 

struct timespec now;
ts.tv_sec = now.tv_sec + ms / 1000 + ( now.tv_nsec + (ms % 1000) \* 1000000 ) / (1000_1000_1000); 

ts.tv_nsec = ( now.tv_nsec + (ms % 1000) \* 1000000 ) % (1000 \* 1000 *1000);

example：
  ts.tv_sec = 0   ts.tv_nsec = 999 000 000   ms = 2  

then after calculate,  the right time should be : 
ts.tv_sec = 1  ts.tv_nsec = 001 000 000
but you code will calculate the time will be wrong . 

**The same as line 507, in function sem_lock_wait()** 
if any question, contact me 243818817@qq.com

**Comment by gozfree** [comment]
@CMShuyuhui Thanks a lot, I have fix it.
If any bugs found in libraries, please report it.
