### ISSUE TITLE
Make include guards unique

### ISSUE THREAD

**Issue by elfring** [gozfree/libraries#11]
I find that include guards like "[`LIBTIME_H`](https://github.com/gozfree/libraries/blob/6d6742fbf84b844b3b5fb2ae2ce0d3847d5217a4/libtime/libtime.h#L8)" and "[`QUEUE_H`](https://github.com/gozfree/libraries/blob/6d6742fbf84b844b3b5fb2ae2ce0d3847d5217a4/libptcp/queue.h#L8)" are too short for the safe reuse of your header files (when they belong to an application programming interface).

**Comment by elfring** [comment]
Do you reject this software development concern?

**Comment by gozfree** [comment]
@elfring I will fix it later, each header file have to be modified.
Hope you can report code issues inlcude typo and logic
