### ISSUE TITLE
内存池

### ISSUE THREAD

**Issue by yangdun129** [gozfree/libraries#16]
现在设计一个内存池确实有些显得蛋疼，要是不用C语言，语言已经简化到不用关心内存是在堆内存还是在栈内存上了，内存管理算法这种高级货真是只为情怀而来

**Comment by gozfree** [comment]
是的，所以一直没有动力写

**Comment by yangdun129** [comment]
多说一句，我实现过你描述中的内存池，或许功能还要强大一点，做个小APP不用，做大型系统还是必须具备的，特别是几百人要在这个平台上同时编程的时候，可惜就是这么多年没遇到过这么大的新平台项目了，很多功夫成了屠龙之技
