### ISSUE TITLE
Compile libdebug.c errpr

### ISSUE THREAD

**Issue by xuniuer** [gozfree/libraries#18]
libdebug.c:75:5: error: ‘SIGUNUSED’ undeclared here (not in a function); did you mean ‘SI_USER’?
     SIGUNUSED /* 31 */
     ^~~~~~~~~
     SI_USER

Under Ubuntu 18.04, try to compile libraries, above is error information. How to fix it? 
Thanks.

**Comment by xuniuer** [comment]
I check the error and find there is a solution - just to delete the deprecated declaration.

refer to: https://github.com/clearcontainers/shim/issues/68

**Comment by gozfree** [comment]
Thanks!
Delete SIGUNUSED declaration is ok，it comes from "/usr/include/bits/signum.h" of Ubuntu 16.04
