### ISSUE TITLE
libipc compile error

### ISSUE THREAD

**Issue by xuniuer** [gozfree/libraries#19]
libipc compile error as follows:

> msgq_posix.c: In function ‘_mq_notify_update’:
> msgq_posix.c:69:23: error: ‘SIGEV_THREAD’ undeclared (first use in this function); did you mean ‘EVENT_READ’?
>      sv.sigev_notify = SIGEV_THREAD;
>                        ^~~~~~~~~~~~
>                        EVENT_READ
> msgq_posix.c:69:23: note: each undeclared identifier is reported only once for each function it appears in
> make: *** [msgq_posix.o] Error 1
> ==== build linux libipc failed

I fix it by adding #include <signal.h> in the file.

**Comment by gozfree** [comment]
Thanks, I have added it. It seems need more compile compatibility on ubuntu 18.04
