### ISSUE TITLE
license issue

### ISSUE THREAD

**Issue by ktsaou** [gozfree/libraries#4]
Hi, nice work you have done here!

GPL v2 is somewhat problematic. It cannot be linked against GPLv3 code: http://gplv3.fsf.org/dd3-faq

I suggest to either release this as GPLv2+, or LGPL. LGPL is more appropriate for a library.

**Comment by gozfree** [comment]
@ktsaou Thanks for your nice advice, I have changed the license to LGPL and GPLv3

**Comment by chisheng** [comment]
gplv3和lgpl兼容么？如果只是做为一个库为什不只用lgpl啊？

**Comment by gozfree** [comment]
@chisheng GPLv3似乎存在争议，的确LGPL更适合库的发布，感谢建议。但是对于ffmpeg源码的license里，GPLv2，GPLv3，LGPL也是共存的。

**Comment by gozfree** [comment]
@chisheng 已改为只支持LGPL，感谢！
