### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [gozfree/libraries#5]
I would like to point out that identifiers like "[`_LIBDEBUG_H_`](https://github.com/gozfree/libraries/blob/5837f2437f25d0491b6d25974e99823c4708bec7/libdebug/libdebug.h#L8)" and "[`_LIBLIGHTLIB_H_`](https://github.com/gozfree/libraries/blob/3d2453fefe5a5d64d9b47099e0fc428cf3885e86/liblightlib.h#L8)" [do eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by gozfree** [comment]
@elfring Thanks for your nice advice, but I think it is a issue about coding style, linux kernel header files also define like "_LINUX_ACPI_GPIO_H_", so I will not change it. Anyway, thanks a lot.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by gozfree** [comment]
@elfring Thanks for your report, I have refine the code style. If any bugs, please report to me.

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/gozfree/libraries/commit/6d6742fbf84b844b3b5fb2ae2ce0d3847d5217a4 "Deletion of some underscores").
