### ISSUE TITLE
liblog.c bug report

### ISSUE THREAD

**Issue by CMShuyuhui** [gozfree/libraries#6]
你好，我在您liblog.c 的get_proc_name 函数中，觉得有两处地方不妥，您看看是否正确

line 191 原 proc = (char *)calloc(1, i);   应改为   proc = (char *)calloc(1, ret - i);
line 193 原 strncpy(proc, ptr, i); 应改为 strncpy(proc, ptr, ret - i);

测试场景：(当proc_name 长度大于 路径长度时，原有代码功能就不对了。)
example： /home/proc_name_test.out

**Comment by gozfree** [comment]
@CMShuyuhui 感谢report bug，已fix
