### ISSUE TITLE
liblog.c bug report

### ISSUE THREAD

**Issue by CMShuyuhui** [gozfree/libraries#8]
hello , there is a bug in your liblog module source:
liblog.c    get_proc_name()   line 191 : proc = (char *)calloc(1, i);  
=======> proc = (char *)calloc(1, ret - i);

liblog.c    get_proc_name()   line 193 : strncpy(proc, ptr, i);
=========> strncpy(proc, ptr, ret - i);

bug report : 
in order to prevent the follow issue

/home/liblogtest.out

if any question or my report is wrong , please  contact me 243818817@qq.com for email, thanks

**Comment by gozfree** [comment]
@CMShuyuhui Thanks, you are right, I have fix it with your patch.
