### ISSUE TITLE
optimize the liblog splite feature 

### ISSUE THREAD

**Issue by CMShuyuhui** [gozfree/libraries#9]
hello , I have reviewed the liblog.c  and I personally think that the _log_write() function could be optimized.
your code are bellow:(from line 382)
log_get_time(_log_name_time, sizeof(_log_name_time), 1);
snprintf(_log_name, sizeof(_log_name), "%s%s_%s",
                _log_path, _log_name_prefix, _log_name_time);
 _log_open(_log_name);
 fprintf(stderr, "splited file %s\n", _log_name);

but I think they can may be:
log_get_time(_log_name_time, sizeof(_log_name_time), 1);
        char log_rename[FILENAME_LEN];
snprintf(log_rename, sizeof(log_rename), "%s%s_%s",
                _log_path, _log_name_prefix, _log_name_time);
int ret = rename(_log_name,log_rename );
if (ret == -1)
{
      fprintf(stderr, "log file splited rename error:%s\n",log_rename );
}
 _log_open(_log_name);

In the real production environment, maybe we want to splite the log file to a new renamed file,and connitue to write on the file with old name. So in the code , I suggest to add a rename() function.
Of course, it's all up to you decide.

My English is limited ,if any question , you can contact me 243818817@qq.com, thanks!

**Comment by gozfree** [comment]
@CMShuyuhui Thanks for your great advice, the feature is like rsyslog behaviour, and I just rename the old file with timestamp suffix.
It's easy to understand it, I'm a Chinese guy, haha
